### PR TITLE
chore: update doc links from googleapis.dev to cloud.google.com

### PR DESCRIPTION
**Pull request by dandhlee**
Updating the reference documentation website from googleapis.dev to cloud.google.com for the index pages. Also updating references in the README.

### CODE REVIEW

**Comment by grayside** [comment]
This change is going from https://googleapis.dev/python/cloudscheduler/latest/index.html to https://cloud.google.com/python/docs/reference/cloudscheduler/latest. Maybe I'm misunderstanding something, isn't this a significant regression in the information presented to users?

**Comment by dandhlee** [comment]
If you're concerned about the amount of information presented in that specific page (lack of info on c.g.c versus googleapis.dev), it's being tracked in https://github.com/googleapis/sphinx-docfx-yaml/issues/106 and I'll be resolving this soon. There are improved sections such as the signatures and parameters being displayed better, so hopefully it won't feel like a total regression on all sides.

If you feel that the experience on c.g.c is lacking on any other areas please file an issue in the sphinx plugin repo and I'll do my best to make it better!

**Comment by busunkim96** [comment]
@dandhlee https://cloud.google.com/python/docs/reference/cloudscheduler/latest/google.cloud.scheduler_v1.services.cloud_scheduler looks like it's missing the services documentation (equivalent to https://googleapis.dev/python/cloudscheduler/latest/scheduler_v1/cloud_scheduler.html). I spot checked a few other APIs and found they're missing the `service` documentation as well. Did something change in the templates?

**Comment by dandhlee** [comment]
@busunkim96 They should be recovered within few hours! They were indeed missing because of the exception not being handled well from the `format_code` update in the plugin, but has been fixed with the latest 1.3.2 release.

**Comment by dandhlee** [comment]
Closing until the issue on plugin repo is resolved.

**Pull request closed without merging**
